export const playgrounds = [
  { slug:"park-circle-inclusive", name:"Park Circle Inclusive Playground", hood:"North Charleston", addr:"4800 Park Circle, North Charleston, SC", desc:"The world's largest inclusive playground — 55,000 sq ft designed for every child of every ability. Fully fenced with shade sails throughout.", longDesc:"Opened November 2023, this 55,000-square-foot playground is designed for children of all developmental and physical abilities. Fully fenced with shade sails, multiple age zones, towering slides, playhouses, climbing structures, and abundant seating.", ages:"All ages", cost:"Free", rating:5, emoji:"🌈", fenced:true, shade:true, restrooms:true, parking:true, splash:false, accessible:true, tags:["inclusive","fenced","shaded"], tip:"Arrive early on weekends. The entire space is fenced so toddlers can't wander off!", features:["Inclusive equipment","Multiple play zones","Towering slides","Playhouses","Sensory play"], lat:32.8865, lng:-80.0059 },
  { slug:"palmetto-islands", name:"Palmetto Islands County Park", hood:"Mount Pleasant", addr:"444 Needlerush Pkwy, Mt Pleasant, SC 29464", desc:"Sprawling county park with a 50-foot observation tower, rock wall, shaded playground, and Splash Island waterpark.", longDesc:"A family favorite featuring the Big Toy Playground with 50-foot observation tower and rock wall. Spacious shaded playground with swings, slides, sandbox. Covered picnic tables with grills for birthday parties. Splash Island waterpark in warmer months.", ages:"2–12", cost:"$2/person", rating:5, emoji:"🏝️", fenced:false, shade:true, restrooms:true, parking:true, splash:true, accessible:false, tags:["waterpark","climbing","nature"], tip:"Bring a change of clothes — kids end up at the splash pad. Book the picnic area for parties.", features:["50-ft observation tower","Rock climbing wall","Splash Island waterpark","Sandbox","Nature trails"], lat:32.8348, lng:-79.8268 },
  { slug:"james-island-county-park", name:"James Island County Park", hood:"James Island", addr:"871 Riverland Dr, Charleston, SC 29412", desc:"Three age-specific play areas, spray play fountain, climbing wall, and Whirlin' Waters — the Lowcountry's best waterpark.", longDesc:"One of Charleston's crown jewels with three playground areas by age group, seasonal spray play fountain, Whirlin' Waters Adventure Waterpark, miles of trails, dog park, and fishing lakes.", ages:"All ages", cost:"$2/person", rating:5, emoji:"🎢", fenced:false, shade:true, restrooms:true, parking:true, splash:true, accessible:true, tags:["waterpark","multi-age","dog park"], tip:"The toddler area is well-separated from big kids. Don't miss the Holiday Festival of Lights in winter!", features:["Three age-specific play areas","Whirlin' Waters waterpark","Spray play fountain","Climbing wall","Dog park","Fishing lakes"], lat:32.7397, lng:-79.9709 },
  { slug:"waterfront-pirate-playground", name:"Mt Pleasant Memorial Waterfront Park", hood:"Mount Pleasant", addr:"99 Harry M Hallman Jr Blvd, Mt Pleasant, SC", desc:"Iconic pirate-ship playground beneath the Ravenel Bridge with harbor views, dolphin watching, and a fishing pier.", longDesc:"One of the most iconic playgrounds in the Lowcountry — a pirate-ship theme with three play zones, nets, towers, and slides. Adjacent pier for fishing and dolphin-watching. Stunning harbor views.", ages:"2–12", cost:"Free", rating:5, emoji:"🏴‍☠️", fenced:false, shade:false, restrooms:true, parking:true, splash:false, accessible:false, tags:["pirate","waterfront","views"], tip:"Bring binoculars for dolphin spotting! Best for kids who are a little more independent.", features:["Pirate ship theme","Three play zones","Climbing nets & towers","Fishing pier","Harbor views"], lat:32.7855, lng:-79.9063 },
  { slug:"hampton-park", name:"Hampton Park Playground", hood:"Downtown Charleston", addr:"30 Mary Murray Dr, Charleston, SC 29403", desc:"Shaded playground in Charleston's largest 60-acre park, surrounded by gardens and duck ponds.", longDesc:"Nestled within 60-acre Hampton Park, this well-maintained playground has soft play surfaces and quality equipment. Stroller-friendly loop path, duck ponds, and botanical gardens.", ages:"1–8", cost:"Free", rating:4, emoji:"🦆", fenced:false, shade:true, restrooms:true, parking:true, splash:false, accessible:true, tags:["scenic","gardens","downtown"], tip:"Bring a blanket — one of the best picnic spots in town. Gorgeous azaleas in spring.", features:["Modern equipment","Stroller loop path","Duck ponds","Botanical gardens"], lat:32.7984, lng:-79.9476 },
  { slug:"hazel-parker", name:"Hazel Parker Playground", hood:"Downtown Charleston", addr:"70 East Bay St, Charleston, SC 29401", desc:"Hidden gem near the Battery with separate toddler and big kid areas, shaded by mature trees.", longDesc:"Just steps from the Battery, two separate play areas for toddlers and older kids. Shaded by mature trees, perfect pit stop during a downtown stroll.", ages:"1–10", cost:"Free", rating:4, emoji:"🌳", fenced:false, shade:true, restrooms:false, parking:false, splash:false, accessible:false, tags:["downtown","hidden gem","walkable"], tip:"Perfect mid-afternoon break during a downtown tour. Walk to the Battery for the cannons!", features:["Toddler zone","Big kid zone","Mature tree shade","Near the Battery"], lat:32.7700, lng:-79.9271 },
  { slug:"wannamaker-county-park", name:"Wannamaker County Park", hood:"North Charleston", addr:"8888 University Blvd, N Charleston, SC 29406", desc:"Two playgrounds, seasonal splash zone, miles of trails, disc golf, and an off-leash dog park.", longDesc:"Two separate playgrounds, seasonal sprinkler area, miles of walking/biking trails, disc golf course, sports fields, and off-leash dog park.", ages:"All ages", cost:"$2/person", rating:4, emoji:"🛝", fenced:false, shade:true, restrooms:true, parking:true, splash:true, accessible:true, tags:["trails","disc golf","dog park"], tip:"The boardwalk through the wetlands is stroller-friendly and beautiful.", features:["Two playgrounds","Sprinkler area","Disc golf","Walking & biking trails","Dog park"], lat:32.9187, lng:-80.0770 },
  { slug:"ackerman-park", name:"Ackerman Park", hood:"West Ashley", addr:"55 Sycamore Ave, Charleston, SC 29407", desc:"Cozy neighborhood gem with modern climbing equipment, spinning structures, and a dog park next door.", longDesc:"Hidden gem in West Ashley with modern climbing equipment, slides, spinning structures, large grassy field, and adjacent dog park.", ages:"3–10", cost:"Free", rating:4, emoji:"🐕", fenced:false, shade:false, restrooms:false, parking:true, splash:false, accessible:false, tags:["modern","dog-friendly","compact"], tip:"Limited shade — bring water, sunscreen, hats. Mornings and late afternoons best in summer.", features:["Modern climbing equipment","Spinning structures","Open grassy field","Adjacent dog park"], lat:32.7787, lng:-79.9850 },
  { slug:"west-ashley-park", name:"West Ashley Park", hood:"West Ashley", addr:"1500 Sam Rittenberg Blvd, Charleston, SC 29407", desc:"Sprawling playground with climbing webs, tunnels, toddler area, ball fields, fishing dock, and trails.", longDesc:"One of Charleston's largest municipal parks with climbing webs, tunnels, dedicated toddler area, ball fields, fishing dock, and miles of walking trails.", ages:"1–12", cost:"Free", rating:4, emoji:"🎣", fenced:false, shade:true, restrooms:true, parking:true, splash:false, accessible:true, tags:["trails","fishing","multi-age"], tip:"There's a shallow creek near the trails — bring a change of clothes!", features:["Climbing webs","Tunnels","Toddler area","Fishing dock","Walking trails"], lat:32.7720, lng:-79.9893 },
  { slug:"tiedemann-park", name:"Tiedemann Park", hood:"Downtown Charleston", addr:"75 Elizabeth St, Charleston, SC 29403", desc:"Small downtown playground near the Visitors Center with a nature center showcasing reptiles.", longDesc:"Just around the block from the Charleston Visitors Center. Small but charming with a nature center featuring reptiles and amphibians.", ages:"2–8", cost:"Free", rating:3, emoji:"🦎", fenced:false, shade:true, restrooms:false, parking:false, splash:false, accessible:false, tags:["downtown","nature","compact"], tip:"Perfect first stop after arriving in Charleston. One block from King Street for lunch.", features:["Playground equipment","Nature center","Reptile exhibits"], lat:32.7899, lng:-79.9375 },
  { slug:"moultrie-playground", name:"Moultrie Playground", hood:"Downtown Charleston", addr:"41 Ashley Ave, Charleston, SC 29401", desc:"Renovated 2021 playground near Colonial Lake with modern equipment, basketball, and pickleball.", longDesc:"Renovated in 2021 next to Colonial Lake. State-of-the-art equipment, basketball half-court, pickleball court, new seating and picnic areas.", ages:"2–10", cost:"Free", rating:4, emoji:"🏀", fenced:false, shade:false, restrooms:false, parking:false, splash:false, accessible:true, tags:["downtown","modern","sports"], tip:"Walk around Colonial Lake afterward — a beautiful flat loop for strollers and scooters.", features:["Modern equipment","Basketball half-court","Pickleball court","Colonial Lake views"], lat:32.7785, lng:-79.9403 },
  { slug:"folly-pirates-cove", name:"Pirates Cove Playground", hood:"Folly Beach", addr:"55 Center St, Folly Beach, SC 29439", desc:"Shady beachside playground on Folly with a skate park, table tennis, and that classic Folly vibe.", longDesc:"Timothy M. Goodwin Pirates Cove captures the Folly spirit. Shaded playground, small active skate park, table tennis, gazebo, and steps from the beach.", ages:"2–14", cost:"Free", rating:4, emoji:"🏖️", fenced:false, shade:true, restrooms:true, parking:true, splash:false, accessible:false, tags:["beach","skatepark","shaded"], tip:"Hit the playground first, then walk to the beach. Kids get the best of both worlds!", features:["Playground","Skate park","Table tennis","Gazebo","Near beach"], lat:32.6552, lng:-79.9404 },
  { slug:"sullivans-stith-park", name:"J. Marshall Stith Park", hood:"Sullivan's Island", addr:"1804 Middle St, Sullivan's Island, SC 29482", desc:"Island playground with slides, a big toy park, playhouse, tennis courts, and soccer field — steps from the beach!", longDesc:"Located in the heart of Sullivan's Island with slides, big toy park, playhouse, tennis courts, hitting wall, and soccer field. A short walk to the beach.", ages:"2–10", cost:"Free", rating:4, emoji:"🏝️", fenced:false, shade:true, restrooms:true, parking:true, splash:false, accessible:false, tags:["island","beach","tennis"], tip:"After the playground, walk to the beach for a perfect Sullivan's Island afternoon.", features:["Slides","Big toy park","Playhouse","Tennis courts","Soccer field"], lat:32.7634, lng:-79.8527 },
  { slug:"iop-county-park-playground", name:"Isle of Palms County Park", hood:"Isle of Palms", addr:"1 14th Ave, Isle of Palms, SC 29451", desc:"Beachside county park with playground, lifeguards, showers, bathrooms, and snack shack — steps from the sand.", longDesc:"The most convenient beach park in Charleston. Playground equipment, lifeguards, showers, restrooms, snack shack, and paid parking (free with Gold Pass).", ages:"All ages", cost:"$10 parking", rating:4, emoji:"⛱️", fenced:false, shade:false, restrooms:true, parking:true, splash:false, accessible:true, tags:["beach","lifeguards","snack bar"], tip:"Arrive before 10 AM in summer. Gold Pass covers parking!", features:["Playground","Lifeguards","Showers","Snack shack","Beach access"], lat:32.7867, lng:-79.7797 },
  { slug:"gadsdenboro-park", name:"Gadsdenboro Park", hood:"Downtown Charleston", addr:"30 Concord St, Charleston, SC 29401", desc:"Newer playground near the SC Aquarium — great for burning off energy after seeing sea turtles.", longDesc:"Located near the South Carolina Aquarium on Concord Street. Newer play area, not much shade, but perfect for post-aquarium play.", ages:"2–8", cost:"Free", rating:3, emoji:"🐢", fenced:false, shade:false, restrooms:false, parking:false, splash:false, accessible:true, tags:["downtown","aquarium","walkable"], tip:"Combine with an Aquarium visit — it's right next door!", features:["Modern equipment","Near SC Aquarium","Downtown location"], lat:32.7850, lng:-79.9255 },
  { slug:"mary-utsey", name:"Mary Utsey Playground", hood:"West Ashley", addr:"947 Orange Grove Rd, Charleston, SC 29407", desc:"Large fenced-in play area with lots of shade, restrooms, and tennis courts. Never too crowded.", longDesc:"A large fenced playground in West Ashley with lots of shade, on-site restrooms, tennis courts, and picnic tables. Relaxed and rarely crowded.", ages:"2–10", cost:"Free", rating:4, emoji:"🌿", fenced:true, shade:true, restrooms:true, parking:true, splash:false, accessible:false, tags:["fenced","shaded","quiet"], tip:"A great park when you want a chill, uncrowded experience. Bring a picnic!", features:["Fenced perimeter","Shade trees","Restrooms","Tennis courts","Picnic tables"], lat:32.7761, lng:-79.9746 },
  { slug:"alhambra-playground", name:"Alhambra Playground", hood:"Mount Pleasant", addr:"Venning St, Mt Pleasant, SC 29464", desc:"Large shaded retreat in the Old Village with mossy oaks and spectacular views of downtown across the harbor.", longDesc:"In Mt Pleasant's picturesque Old Village, shaded by mossy oaks with spectacular views of downtown Charleston across the harbor.", ages:"2–10", cost:"Free", rating:4, emoji:"🌊", fenced:false, shade:true, restrooms:false, parking:true, splash:false, accessible:false, tags:["old village","views","shaded"], tip:"One of the most scenic playgrounds in Charleston. Great photo ops with the downtown skyline!", features:["Mossy oak shade","Harbor views","Old Village charm"], lat:32.7826, lng:-79.8741 },
  { slug:"lenevar-playground", name:"Lenevar Playground", hood:"West Ashley", addr:"1100 Playground Rd, Charleston, SC 29407", desc:"A neighborhood park in West Ashley with a big green space, playground equipment, and a relaxed feel.", longDesc:"A neighborhood favorite in West Ashley with a large green space perfect for running, playground equipment, and a relaxed community atmosphere.", ages:"2–10", cost:"Free", rating:3, emoji:"🌱", fenced:false, shade:true, restrooms:false, parking:true, splash:false, accessible:false, tags:["neighborhood","green space","quiet"], tip:"Lots of room to run! Bring a frisbee or soccer ball alongside playground time.", features:["Large green space","Playground equipment","Neighborhood feel"], lat:32.7800, lng:-79.9900 },
];

export const beaches = [
  { slug:"isle-of-palms", name:"Isle of Palms", emoji:"🏖️", distance:"9 mi from downtown", vibe:"Family-friendly haven", desc:"The most popular family beach near Charleston. IOP County Park has lifeguards, restrooms, showers, a playground, and snack shack. Gold Pass covers parking. Plenty of beachfront restaurants on Ocean Blvd. Dogs allowed year-round.", parking:"County Park: $10-20 (free w/ Gold Pass). Street parking available.", tips:["Arrive before 10 AM in summer for parking","County park has lifeguards, showers, playground","Ocean Blvd restaurants great for post-beach meals","Dogs allowed year-round on the beach"] },
  { slug:"sullivans-island", name:"Sullivan's Island", emoji:"🐚", distance:"9 mi from downtown", vibe:"Quiet & pristine — the locals' favorite", desc:"Calm waves, tidal pools (gullies) perfect for little kids, and an uncrowded feel. No public restrooms or showers. Great restaurants nearby including Poe's Tavern and Mex 1 Coastal Cantina.", parking:"Free street parking (limited — arrive early)", tips:["Station 22 has the best gullies/tidal pools for kids","No public restrooms — plan accordingly","Keep a jug of water in the car for sandy toes","Station 18 has views of downtown Charleston"] },
  { slug:"folly-beach", name:"Folly Beach", emoji:"🏄", distance:"13 mi from downtown", vibe:"Funky surf town — The Edge of America", desc:"Charleston's most colorful beach. County park has lifeguards, restrooms, and rentals. Center Street has surf shops, restaurants, and the iconic Pineapple Hut for dole whips. Best surfing at The Washout.", parking:"County Park: varies (free w/ Gold Pass). Street parking limited.", tips:["Best surfing in SC at The Washout","County park has lifeguards and chair/umbrella rentals","Taco Boy and Lost Dog Cafe are family favorites","Go early or after 4 PM to avoid traffic"] },
  { slug:"kiawah-beachwalker", name:"Kiawah Beachwalker Park", emoji:"🦀", distance:"25 mi from downtown", vibe:"Serene nature retreat", desc:"Pristine, less-crowded beach. Beachwalker Park has boardwalk, lifeguards (seasonal), restrooms, showers, and rentals. Gentle waves perfect for little ones. Amazing for sand dollars and shell collecting.", parking:"$7 weekdays / $10 weekends (free w/ Gold Pass). Only 150 spots.", tips:["Arrive before 10:30 AM — only 150 parking spots","Gentlest waves — ideal for toddlers","Great sand dollar hunting","Stop at Freshfields Village for food on the way home"] },
  { slug:"edisto-beach", name:"Edisto Beach", emoji:"🐢", distance:"~1 hr from downtown", vibe:"Peaceful & unspoiled", desc:"Less developed and uncrowded — the nature lover's beach. State Park has camping, cabins, hiking, and gorgeous beaches. Sea turtle nesting season May–October. 4.5 miles of pristine shoreline.", parking:"State Park: $8/adult. Town beach: free street parking.", tips:["Perfect for a full day trip or overnight camping","Sea turtle season: May–Oct (hatchlings Jul–Oct)","State Park has cabins for overnight stays","The most uncrowded beach option near Charleston"] },
];

export const activities = [
  { slug:"sc-aquarium", name:"South Carolina Aquarium", emoji:"🐠", category:"Museums", addr:"100 Aquarium Wharf, Charleston", price:"~$35/adult, $25/child", ages:"All ages", desc:"385,000-gallon ocean tank, touch tanks, sea turtle hospital, albino alligator, and 4D theater. On the harbor near the Ravenel Bridge.", url:"https://scaquarium.org", tip:"Tour the Sea Turtle Hospital — it's worth the extra cost. Combine with nearby Waterfront Park." },
  { slug:"childrens-museum", name:"Children's Museum of the Lowcountry", emoji:"🏰", category:"Museums", addr:"25 Ann St, Charleston", price:"$15 ($3 w/ SNAP/WIC)", ages:"0–10", desc:"Pirate ship, medieval castle, kid-sized grocery store, water play, art studio. Best for imaginative play. Free for children under 1.", url:"https://explorecml.org", tip:"Be prepared to stay a while — once kids start, it's tough to leave." },
  { slug:"patriots-point", name:"Patriots Point Naval Museum", emoji:"⚓", category:"History", addr:"40 Patriots Point Rd, Mt Pleasant", price:"~$29/adult, $19/child", ages:"5+", desc:"Explore the USS Yorktown aircraft carrier, WWII destroyer, and submarine. Vietnam base replica and Medal of Honor Museum.", url:"https://patriotspoint.org", tip:"Great for older kids. Grab lunch at Shem Creek afterward — kids love watching the pelicans." },
  { slug:"charleston-museum", name:"The Charleston Museum", emoji:"🏛️", category:"Museums", addr:"360 Meeting St, Charleston", price:"~$15/adult, $7/child", ages:"3+", desc:"America's first museum. Kidstory exhibit, megalodon jawbone, colonial clothing to try on, scavenger hunts, and STEAM Saturdays.", url:"https://charlestonmuseum.org", tip:"The Kidstory exhibit is a hit. Free STEAM Saturdays for members." },
  { slug:"magnolia-plantation", name:"Magnolia Plantation & Gardens", emoji:"🌺", category:"Nature", addr:"3550 Ashley River Rd, Charleston", price:"~$25/adult, $15/child", ages:"All ages", desc:"Fairy gardens, storybook walk, petting zoo, and centuries-old gardens. The Children's Garden has fairy villages, gnomes, and woodland creatures.", url:"https://magnoliaplantation.com", tip:"The fairy garden is magical. Split up — adults tour the house while kids do the petting zoo." },
  { slug:"waterfront-park", name:"Waterfront Park & Pineapple Fountain", emoji:"⛲", category:"Free", addr:"1 Vendue Range, Charleston", price:"Free", ages:"All ages", desc:"Iconic Pineapple Fountain where kids splash, porch swings overlooking the harbor, gorgeous waterfront views. A Charleston must-visit.", url:"", tip:"Pack swimsuits — kids will end up in the fountain. Great for a post-dinner stroll." },
  { slug:"riverdogs", name:"Charleston RiverDogs Baseball", emoji:"⚾", category:"Sports", addr:"360 Fishburne St, Charleston", price:"$10–25", ages:"All ages", desc:"Minor league baseball on the Ashley River. Affordable, fun atmosphere with promotions, fireworks, and kid-friendly concessions.", url:"https://riverdogs.com", tip:"Thursday games often have specials. Lawn seating is perfect for wiggly kids." },
  { slug:"carriage-ride", name:"Horse-Drawn Carriage Tour", emoji:"🐴", category:"Tours", addr:"Various downtown locations", price:"~$35/adult, $20/child", ages:"All ages", desc:"Ride through historic downtown in an old-fashioned horse-drawn carriage. Kids wave at everyone and love every minute.", url:"", tip:"Evening rides are cooler in summer. Kids might not remember the history, but they'll remember the horse!" },
  { slug:"fort-sumter", name:"Fort Sumter National Monument", emoji:"🏰", category:"History", addr:"Ferry from Liberty Square", price:"~$25/adult, $16/child (ferry)", ages:"5+", desc:"Harbor ferry to the fort where the Civil War began. Junior Ranger program. Beautiful boat ride with harbor views.", url:"https://nps.gov/fosu", tip:"The ferry ride is half the fun. Ask about the Junior Ranger program at the dock." },
  { slug:"cypress-gardens", name:"Cypress Gardens", emoji:"🛶", category:"Nature", addr:"3030 Cypress Gardens Rd, Moncks Corner", price:"~$10/adult, $5/child", ages:"All ages", desc:"Hidden gem — flat-bottom boat rides through ancient cypress swamps, butterfly house, aquarium. Worth the 30-min drive.", url:"", tip:"The boat ride through the cypress swamp is unforgettable. Bring bug spray!" },
  { slug:"fire-museum", name:"North Charleston Fire Museum", emoji:"🚒", category:"Museums", addr:"4975 Centre Pointe Dr, N Charleston", price:"~$8/adult, $5/child", ages:"2–8", desc:"Vintage fire trucks, fire station play area, and a big slide. Toddler obsession guaranteed. Perfect rainy day activity.", url:"", tip:"Little ones go wild for the vintage trucks and the slide." },
];

export const passes = [
  { slug:"gold-pass", name:"Charleston County Parks Gold Pass", emoji:"🏅", price:"$99 ($84 County residents, $69 Seniors 60+)", desc:"The best deal for active families. Gets your entire car into all county parks including beach parks.", includes:["Free entry to all county parks for everyone in your vehicle","Free beach parking at IOP, Folly, and Kiawah county parks","$15 off SC Aquarium annual membership","Access to Holiday Festival of Lights"], howTo:"Buy online at CharlestonCountyParks.com, at any park office, or call 843-795-4386.", proTip:"If you go to the beach 3+ times in summer, it pays for itself. Best family purchase in Charleston." },
  { slug:"library-gold-pass", name:"Free Gold Pass via Library", emoji:"📚", price:"Free (with library card)", desc:"CCPL has Gold Passes available for checkout at every branch! Check one out with your adult library card for one week.", includes:["Same benefits as a purchased Gold Pass","One week checkout period","Renewable up to 2 times","Available at all 18 CCPL branches + bookmobile"], howTo:"Visit any CCPL branch with your adult library card. Ask at the desk.", proTip:"High demand — call your branch first. Tuesday mornings tend to have the best selection." },
  { slug:"splash-pass", name:"Splash Pass", emoji:"💦", price:"Starting ~$60 (Super) / ~$45 (Basic)", desc:"Season pass for waterparks. Super covers all three; Basic covers two.", includes:["All-summer waterpark access","Free gate entrance during waterpark season","Discounted guest admission"], howTo:"Buy online at CharlestonCountyParks.com or call 843-795-4386.", proTip:"If you'll visit waterparks 3+ times, the pass saves money." },
  { slug:"individual-pass", name:"Individual Park Pass", emoji:"🎫", price:"$40 ($30 County residents)", desc:"Annual pass for one person — walking, biking, or driving into county parks.", includes:["Entry to James Island, Palmetto Islands, Wannamaker","Access to Caw Caw, Laurel Hill, Johns Island trails","Valid one year"], howTo:"Buy online, at park offices, or by phone.", proTip:"Great for solo joggers/bikers. For families, the Gold Pass is better value." },
  { slug:"state-parks-pass", name:"SC State Parks Pass (via Library)", emoji:"🌲", price:"Free (with library card)", desc:"CCPL lends out SC State Parks passes — free vehicle entry to any SC state park.", includes:["Free vehicle entry to all SC state parks","Two week checkout","Great for Edisto, Hunting Island, etc."], howTo:"Check out from any CCPL branch with your adult library card.", proTip:"Perfect for an Edisto day trip or Hunting Island camping weekend." },
];

export const libraries = [
  { slug:"main", name:"Main Library (Calhoun St)", addr:"68 Calhoun St, Charleston, SC 29401", phone:"843-805-6930", desc:"Flagship downtown branch. Large children's section, weekly storytime, STEAM activities. Gold Pass & State Parks Pass checkout.", features:["Children's section","Weekly storytime","Gold Pass checkout","State Parks Pass","Meeting rooms"] },
  { slug:"mt-pleasant", name:"Mt Pleasant Library", addr:"1133 Mathis Ferry Rd, Mt Pleasant, SC 29464", phone:"843-849-6161", desc:"Popular family branch with excellent children's programming, summer reading, and pass checkouts.", features:["Children's programs","Summer reading","Gold Pass checkout","Study rooms"] },
  { slug:"west-ashley", name:"West Ashley Library", addr:"45 Windermere Blvd, Charleston, SC 29407", phone:"843-766-6635", desc:"Well-loved branch with active children's programming and toddler storytimes.", features:["Toddler storytime","Children's events","Gold Pass checkout"] },
  { slug:"otranto", name:"Otranto Regional Library", addr:"2261 Otranto Rd, N Charleston, SC 29406", phone:"843-572-4094", desc:"Large North Charleston branch with children's programming, maker space, and study areas.", features:["Maker space","Children's programs","Gold Pass checkout","Large facility"] },
  { slug:"james-island", name:"James Island Library", addr:"1248 Camp Rd, Charleston, SC 29412", phone:"843-795-6679", desc:"Convenient location near the county park. Great children's section.", features:["Children's section","Near county park","Community events"] },
  { slug:"folly-beach", name:"Folly Beach Library", addr:"55 Center St, Folly Beach, SC 29439", phone:"843-588-2001", desc:"Small charming beach library. Perfect for grabbing books before or after beach time.", features:["Beach location","Children's books","Summer programs"] },
  { slug:"sullivans-island", name:"Sullivan's Island Library", addr:"1820 Ion Ave, Sullivan's Island, SC 29482", phone:"843-883-3914", desc:"Tiny island gem — a cozy spot to browse with kids between beach sessions.", features:["Island setting","Children's collection","Cozy atmosphere"] },
  { slug:"john-l-dart", name:"John L. Dart Library", addr:"1067 King St, Charleston, SC 29403", phone:"843-722-7550", desc:"Historic branch on upper King Street with children's resources and community programs.", features:["Children's section","Community programs","King Street location"] },
];

export const influencers = [
  { name:"Jetset Christina", handle:"@jetsetchristina", followers:"116K", platform:"Instagram", desc:"Charleston-based luxury travel blogger and mom. Named #1 on Travel & Leisure's Top Travel Instagrams. Curated guides, family-friendly resort picks, and the best dining in Charleston.", url:"https://instagram.com/jetsetchristina", category:"Travel & Lifestyle" },
  { name:"Julia Berolzheimer", handle:"@juliaberolzheimer", followers:"1.3M", platform:"Instagram", desc:"Formerly Gal Meets Glam. Charleston mom of two with a Southern Living aesthetic. Home, family, and timeless style.", url:"https://instagram.com/juliaberolzheimer", category:"Home & Family" },
  { name:"Charleston Moms", handle:"@thecharlestonmoms", followers:"14K", platform:"Instagram", desc:"The premier parenting resource since 2015. Events, playground reviews, and weekend roundups for local families.", url:"https://instagram.com/thecharlestonmoms", category:"Parenting" },
  { name:"Littles in the Lowcountry", handle:"@littlesinthelowcountry", followers:"10K+", platform:"Instagram", desc:"Sarah, a Charleston mom and early childhood educator, shares child-friendly activities — parks, restaurants, museums, and weekend events.", url:"https://instagram.com/littlesinthelowcountry", category:"Kids Activities" },
  { name:"Kenzie & Carol Carter", handle:"@kc_doubletake", followers:"180K", platform:"Instagram", desc:"Twin sisters in Charleston sharing everyday outfits, home, mom life, and adventures with matching style.", url:"https://instagram.com/kc_doubletake", category:"Mom Life & Fashion" },
  { name:"Arin Jura", handle:"@arinsolange", followers:"290K+", platform:"Instagram", desc:"Mt Pleasant mom of three. Acclaimed home and lifestyle influencer — organized spaces that coexist with real family life.", url:"https://instagram.com/arinsolange", category:"Home & Organization" },
  { name:"Amy Romfo", handle:"@thecoastaloak", followers:"120K+", platform:"Instagram", desc:"Former nurse turned lifestyle creator. Cozy coastal vibes and family content. Often at Pitt Street Bridge or Old Village playground.", url:"https://instagram.com/thecoastaloak", category:"Coastal Lifestyle" },
  { name:"Megan Stokes", handle:"@meganstokes", followers:"60K+", platform:"Instagram", desc:"Mom of two sharing home design, shopping finds, and Lowcountry family life. Traditional Southern style.", url:"https://instagram.com/meganstokes", category:"Home & Lifestyle" },
  { name:"Kidding Around Charleston", handle:"@kiddingaroundchs", followers:"5K+", platform:"Blog", desc:"In-depth playground reviews, family-friendly spots, and the best things to do with kids in Charleston.", url:"https://kiddingaroundcharleston.com", category:"Kids Activities" },
];

export function getPlaygroundBySlug(slug) { return playgrounds.find(p => p.slug === slug); }
export function getNeighborhoods() { return [...new Set(playgrounds.map(p => p.hood))]; }
